<script>(function(){$('.text-field, .text-area').on({focus:function(){let a=$(this),b=a.val().length;a.siblings('.field-label, .area-label').addClass('active');if(b){a.addClass('active')}},blur:function(){let a=$(this),b=a.val().length;if(!b){a.siblings('.field-label, .area-label').removeClass('active');a.removeClass('active')}},input:function(){let a=$(this),b=a.val().length;if(b){a.addClass('active')}else{a.removeClass('active')}}})})();</script>
<script>document.querySelectorAll(".select-field-label2,.select-field-icon").forEach(e=>e.style.pointerEvents="none")</script>
<script>!function(e){e.forEach((e=>{e.style.pointerEvents="none"}))}(document.querySelectorAll(".field-label"));</script>
<script>!function(){const t=(new Date).getFullYear(),e=[t+1,t+2],n=document.querySelector('select[data-select-type="year-select"]'),o=document.createElement("option");o.value="",o.textContent="Year",o.disabled=!0,o.selected=!0,n.appendChild(o);const c=document.createElement("option");c.value=t,c.textContent=t,n.appendChild(c),[e[0],e[1]].forEach(t=>{const e=document.createElement("option");e.value=t,e.textContent=t,n.appendChild(e)})}();</script>
<script>!function(){fetch("https://ipapi.co/json/").then(e=>e.json()).then(e=>{const t=e.country_name,o=document.querySelector('select[name="Select Country"]'),n=o.options;for(let e=0;e<n.length;e++)if(n[e].textContent===t){o.selectedIndex=e;break}})}();</script>
<script>!function(){window.addEventListener("beforeunload",(e=>(e.preventDefault(),"string"==typeof e.returnValue&&(e.returnValue="Are you sure you want to leave the form?"))),window.onbeforeunload=()=>("string"==typeof event.returnValue)&&"Are you sure you want to leave the form?")}();</script>
<script>!function(){for(var e=document.querySelectorAll("form select"),t=0;t<e.length;t++)for(var s=e[t].querySelectorAll("option"),n=0;n<s.length;n++)s[n].value|| (s[n].disabled=!0)}();</script>
<script>const e=document.querySelector('select[name="Occupation"]');Array.from(e.options).sort((e,t)=>e.textContent.localeCompare(t.textContent)).forEach(e=>e.add(e))</script>
<script>(function(){for(let e=document.querySelectorAll("#select-input-field"),t=document.querySelectorAll(".select-field-label2"),n=0;n<e.length;n++)e[n].addEventListener("change",function(){""!==this.value?(t[n].style.display="block",t[n].classList.add("active-select"),e[n].classList.add("active-select-drop")):(t[n].style.display="block",t[n].classList.remove("active-select"),e[n].classList.remove("active-select-drop"))})})();</script>
<script>for(let e=document.querySelectorAll("select"),t=0;t<e.length;t++)for(let n=e[t].options,r=0;r<n.length;r++)n[r].disabled&&(n[r].selected=!0,1);</script>
<script>(()=>{let a=1,b=document.querySelector(".slider-progress-bar-value"),c=document.querySelector(".slider-nav-next-button"),d=document.querySelector(".slider-nav-back-button"),e=document.querySelector(".count-number"),submitModalTrigger=document.querySelector(".submit-modal-trigger");b.style.transition="width 300ms cubic-bezier(0.4, 0, 0.25, 1)";1===a?(d.style.opacity="0",d.style.pointerEvents="none"):2===a&&(d.style.opacity="1",d.style.pointerEvents="auto"),c.addEventListener("click",()=>{10===a?(submitModalTrigger.click(),c.removeAttribute("fs-mirrorclick-element")):(a++,b.style.width=10*a+"%",e.innerHTML=a,2===a&&(d.style.opacity="1",d.style.pointerEvents="auto"),a<10&&c.setAttribute("fs-mirrorclick-element","trigger-2"))}),d.addEventListener("click",()=>{1!==a&&(a--,b.style.width=10*a+"%",e.innerHTML=a,1===a?(d.style.opacity="0",d.style.pointerEvents="none"):(9===a&&(c.style.opacity="1",c.style.pointerEvents="auto",c.setAttribute("fs-mirrorclick-element","trigger-2")),10===a&&c.removeAttribute("fs-mirrorclick-element")))}),document.querySelectorAll(".select-field-label2, .select-field-icon").forEach(a=>{a.style.pointerEvents="none"})})();</script>
<script>fetch('https://raw.githubusercontent.com/sgzg/src/main/country-region.json').then(response=>response.json()).then(data=>{const countries=data.countries;const selectCountry=document.querySelector('select[name="Select Country"]');const countryOption=document.createElement('option');countryOption.value=null;countryOption.text='Country of Citizenship';countryOption.disabled=true;selectCountry.add(countryOption);countries.forEach(country=>{const option=document.createElement('option');option.value=country.country;option.text=country.country;selectCountry.add(option);});const selectState=document.querySelector('select[name="Select State"]');const stateOption=document.createElement('option');stateOption.value=null;stateOption.text='State / Region / Municipality of Birth ';stateOption.disabled=true;selectState.add(stateOption);selectCountry.addEventListener('change',()=>{selectState.innerHTML='';selectState.add(stateOption);const selectedCountry=selectCountry.value;const states=countries.find(country=>country.country===selectedCountry).states;states.forEach(state=>{const option=document.createElement('option');option.value=state;option.text=state;selectState.add(option);});});}).catch(error=>console.log(error));</script>
<script>document.addEventListener('DOMContentLoaded',()=>{const e=document.querySelector('select[name="disabilities"]'),t=document.querySelector('select[name="disabilityType"]');e.addEventListener('change',()=>{'no'===e.value?(t.value='',t.removeAttribute('required')):(t.value='select a type',t.setAttribute('required',!0))})});</script>
<script>fetch("https://raw.githubusercontent.com/sgzg/src/main/nigeria-lga.min.json").then(response=>response.json()).then(data=>{const stateSelect=document.querySelector('select[name="Select State"]');const lgaSelect=document.querySelector('select[name="lga"]');const placeholderOption=document.createElement('option');placeholderOption.value='';placeholderOption.text='Local Government Area';placeholderOption.disabled=true;placeholderOption.selected=true;lgaSelect.appendChild(placeholderOption);stateSelect.addEventListener('change',()=>{const selectedState=stateSelect.value;const stateData=data.find(item=>item.state===selectedState);if(!stateData){lgaSelect.innerHTML='';lgaSelect.appendChild(placeholderOption);return;}const lgas=stateData.lgas;lgaSelect.innerHTML='';lgaSelect.appendChild(placeholderOption);lgas.forEach(lga=>{const option=document.createElement('option');option.text=lga;lgaSelect.add(option);});});}).catch(error=>console.error(error));</script>
<script>!function(){fetch("https://raw.githubusercontent.com/sgzg/src/main/codes.json").then(r=>r.json()).then((e=>{document.querySelectorAll('select[name="countryCode"]').forEach((s=>{const n=document.createElement("option");n.disabled=!0,n.value="",n.text="Country Code",s.add(n),e.forEach((e=>{const t=document.createElement("option");t.value=e.dial_code,t.text=`${e.name}: ${e.dial_code}`,s.add(t)}))}))}))}();</script>
<script>(()=>{const a=document.querySelector('input[name="Surname"]');a.setAttribute("autocomplete","family-name");const b=document.querySelector('input[name="otherNames"]');b.setAttribute("autocomplete","given-name");const c=document.querySelector('input[name="homeAddress"]');c.setAttribute("autocomplete","street-address home");document.querySelectorAll('input[name="motherName"], input[name="fatherName"], input[name="guardianName"]').forEach(d=>{d.setAttribute("autocomplete","name")});document.querySelectorAll('input[name="motherAddress"], input[name="fatherAddress"], input[name="guardianAddress"]').forEach(e=>{e.setAttribute("autocomplete","home street-address work")});document.querySelectorAll('input[name="motherNo"], input[name="fatherNo"], input[name="guardianNo"]').forEach(f=>{f.setAttribute("autocomplete","tel-national")});document.querySelectorAll('input[name="motherEmail"], input[name="fatherEmail"], input[name="guardianEmail"]').forEach(g=>{g.setAttribute("autocomplete","email")});document.querySelectorAll('input[name="motherOccupation"], input[name="fatherOccupation"], input[name="guardianOccupation"]').forEach(h=>{h.setAttribute("autocomplete","organization-title")})})()</script>

<script>(()=>{const e=document.querySelector('select[name="languages"]'),t=document.createElement('option');t.value=null,t.text="First Language",t.disabled=!0,t.selected=!0,e.appendChild(t),fetch('https://raw.githubusercontent.com/sgzg/src/main/languages.json').then(e=>e.json()).then(t=>{for(const n of t){const s=document.createElement('option');s.value=n.code,s.text=n.name,e.appendChild(s)}})})();</script><script>(()=>{const e=document.querySelectorAll('textarea');e.forEach((e)=>{e.style.resize='none',e.style.webkitResize='none',e.style.overflow='auto'})})();</script>
 